fix: update footer style
kavimaluskam/august-robotics-web pull request #18
Opened 2020-09-29 15:50 UTC by kavimaluskam

referring to issue #13﻿

2020-09-30 08:06 UTC, kavimaluskam commented
updated footer:
![image](https://user-images.githubusercontent.com/19992414/94659448-e335c000-0336-11eb-80d2-e38e4aef70d5.png)

2020-09-30 19:00 UTC, victor77dev commented on src/components/Footer/index.js
> +} from "@material-ui/core"
What rule are you using? Not more than 3 items?

2020-09-30 19:24 UTC, victor77dev requested changes
Using material ui + styled components look a bit complicated. Is this a usual way to do it?🤔

2020-09-30 19:24 UTC, victor77dev commented on src/components/Footer/index.js
> +  margin-top: 0px;
Do we need `0px`? I thought default `margin` is 0?
Also, I think usually you just put `0` instead of `0px` as unit is meaningless.

2020-09-30 19:24 UTC, victor77dev commented on src/components/Footer/index.js
> +  font-size: 18px;
Shouldn't we use `rem` for text?
Indeed I also use in icons, but font should be using `rem` by default? Otherwise the font size selection in browser will not work.

2020-09-30 19:24 UTC, victor77dev commented on src/components/Footer/index.js
> +                    window.open(socialLink.url)
Doesn't look a good idea. I think it's good to use native html element.
If it's link, then use `<a>`. You could wrap the Icon in it or the other way around, I guess.
The navigation and site reader may get crazy if you don't use native html element.

2020-09-30 19:26 UTC, kavimaluskam commented on src/components/Footer/index.js
> +  font-size: 18px;
Oh because i am not very familiarized with `rem` style, and i copy a project with the below material-ui theme:
https://github.com/kavimaluskam/august-robotics-web/blob/master/src/utils/muiTheme.js

2020-09-30 19:28 UTC, kavimaluskam commented on src/components/Footer/index.js
> +                    window.open(socialLink.url)
I use icon button to take the material-ui ripple effect only... 🤔 
So you would prefer native elements with custom styling?

2020-09-30 19:28 UTC, kavimaluskam commented on src/components/Footer/index.js
> +  margin-top: 0px;
Forgot why i use `0px` XD let me check

2020-09-30 19:29 UTC, kavimaluskam commented on src/components/Footer/index.js
> +} from "@material-ui/core"
Default prettier from gatsby starter i guess:
https://github.com/kavimaluskam/august-robotics-web/blob/master/.prettierrc

2020-09-30 19:33 UTC, kavimaluskam commented
@victor77dev 

I think branch of people doing this:
https://material-ui.com/guides/interoperability/#styled-components

But you would prefer native elements with styled-component only? 

In this case I think I need some strong styling templates to start with...🤔 
And I seldom reuse styled-components so i think it's hard

2020-09-30 19:49 UTC, victor77dev commented on src/components/Footer/index.js
> +} from "@material-ui/core"
Which one? My question is starting a new line when deconstructing.
I saw you don't have new line with 3 items up there.
When will you start a new line?

2020-09-30 19:52 UTC, victor77dev commented on src/components/Footer/index.js
> +  font-size: 18px;
Some materials about px vs rem
https://engageinteractive.co.uk/blog/em-vs-rem-vs-px
https://stackoverflow.com/questions/11799236/should-i-use-px-or-rem-value-units-in-my-css

2020-09-30 20:03 UTC, victor77dev commented on src/components/Footer/index.js
> +                    window.open(socialLink.url)
I would say try to wrap it in if possible. Native html elements serve a purpose of its existence.
Browser will know it's a link if you use `<a>` when it's a link, but don't if you use the icon.
```
<a href="...">
<WhiteIconButton>
</WhiteIconButton>
</a>
```
I think this should work🤔

2020-09-30 20:05 UTC, victor77dev commented
> @victor77dev
> 
> I think branch of people doing this:
> https://material-ui.com/guides/interoperability/#styled-components
> 
> But you would prefer native elements with styled-component only?
> 
> In this case I think I need some strong styling templates to start with...🤔
> And I seldom reuse styled-components so i think it's hard

No, I'm just curious about it. (And see if I could copy this =p)

2020-10-01 04:09 UTC, kavimaluskam commented on src/components/Footer/index.js
> +} from "@material-ui/core"
The "new line with 3 items up" is controlled by prettier.
I am probably using the default setting as I don't see any properties in the `.prettierrc`.
Let me check how to configure it.

2020-10-01 04:13 UTC, kavimaluskam commented on src/components/Footer/index.js
> +                    window.open(socialLink.url)
ok so you would prefer `<a href="...">...</a>` in most cases to secure sake. 🤔  let me update

2020-10-01 04:27 UTC, kavimaluskam commented on src/components/Footer/index.js
> +  font-size: 18px;
> However, if the website explicitly sets font-sizes in pixels, a heading set at 30px will always be 30px. That might sound great from a designer/developer point of view - but you’re not the user, stop making websites for yourself.

In this case i think `px` will be more safe for my project? LOL my views and client's view would be the same

2020-10-01 04:37 UTC, kavimaluskam commented on src/components/Footer/index.js
> +} from "@material-ui/core"
I think it is triggered by character 80 line. Probably I will stick with the setting.

2020-10-01 04:41 UTC, kavimaluskam commented on src/components/Footer/index.js
> +                    window.open(socialLink.url)
How would you handle the below code then:

I think it's some shitty one but i havn't think of better solutions
```js
<FooterButton
  key={item.name}
  onClick={event => {
    event.preventDefault()
    if (item.link) {
      item.link.startsWith("/")
        ? navigate(item.link)
        : window.open(item.link)
    }
  }}
>
  {item.name}
</FooterButton>
```

2020-10-01 04:48 UTC, kavimaluskam commented on src/components/Footer/index.js
> +                    window.open(socialLink.url)
Does this one looks better?
```js
{menu.menuItems.map(item => {
    if (!item.link) {
      return (
        <FooterButton key={item.name}>{item.name}</FooterButton>
      )
    }

    if (item.link.startsWith("/")) {
      return (
        <Link key={item.name} to={item.link}>
          <FooterButton>{item.name}</FooterButton>
        </Link>
      )
    }
    return (
      <a
        key={item.name}
        target="_blank"
        rel="noopener noreferrer"
        href={item.link}
      >
        <FooterButton>{item.name}</FooterButton>
      </a>
    )
  })}
</Grid>
))}
```

2020-10-01 16:52 UTC, victor77dev commented on src/components/Footer/index.js
> +  font-size: 18px;
I think this is not a good practice. I will not approve the PR🤣

2020-10-01 16:52 UTC, victor77dev commented on src/components/Footer/index.js
> +                    window.open(socialLink.url)
yes!

2020-10-01 16:57 UTC, victor77dev approved these changes
Looks better.
I'm not that happy with the use of px, but I'm approving this anyway.🤣

2020-10-01 17:45 UTC, kavimaluskam commented on src/components/Footer/index.js
> +                    window.open(socialLink.url)
the if else short term is a tempting trap for me

2020-10-01 18:11 UTC, kavimaluskam commented
Merge first and update `px` later / in next project

2020-10-01 18:11 UTC, merged