feat: add coloring; unify photo size; remove accordion;
kavimaluskam/august-robotics-web pull request #21
Opened 2020-09-30 08:56 UTC by kavimaluskam

referring to issue #19

2020-09-30 19:25 UTC, victor77dev commented on content/en/location.md
> +      - alt: germany-1
wow, germany!

2020-09-30 19:42 UTC, victor77dev requested changes

2020-09-30 19:42 UTC, victor77dev commented on src/components/Location/index.js
> +        infiniteLoop={true}
I think you don't need `{true}` in jsx
```suggestion
        dynamicHeight
        autoPlay
        infiniteLoop
```
should be good enough.

2020-09-30 19:42 UTC, victor77dev commented on src/components/Location/index.js
> +          <StdImage key={index} imageObj={img} />
Bad practice of using index as key.
Would have error with eslint?
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md

2020-09-30 19:42 UTC, victor77dev commented on src/components/Location/index.js
> -}
Why delete the types?😂

2020-09-30 19:42 UTC, victor77dev commented on src/templates/page/location.js
> +        </>
Not sure if it will be more readable if it's explicitly break into
```
if (index === 0) {
return ....
} else {
return. ...
}
```

2020-10-01 04:43 UTC, kavimaluskam commented on src/components/Location/index.js
> -}
Because i think using GraphQL + static query, most types are very standard. Going to drop all the propTypes checking in this project.

2020-10-01 04:43 UTC, kavimaluskam commented on src/templates/page/location.js
> +        </>
Nice one.

2020-10-01 05:06 UTC, kavimaluskam commented on src/components/Location/index.js
> +          <StdImage key={index} imageObj={img} />
No error on eslint but I know it's a bad practice lmao. Let me fix it.

2020-10-01 05:06 UTC, kavimaluskam commented on src/components/Location/index.js
> +        infiniteLoop={true}
true.

2020-10-01 16:55 UTC, victor77dev commented on src/components/Location/index.js
> +        infiniteLoop={true}
You know you could commit my suggestions together directly in github😉

2020-10-01 17:01 UTC, victor77dev commented on src/components/Location/index.js
> +      <Carousel showStatus={false} dynamicHeight autoPlay infiniteLoop>
I think if you don't pass in the props then it will be false?
I mean it's `undefined`, but usually the component will be checking as boolean and behavior as false?
It should look like normal html element.

2020-10-01 17:02 UTC, victor77dev requested changes
Sorry missed the props with false case.

2020-10-01 17:08 UTC, kavimaluskam commented on src/components/Location/index.js
> +        infiniteLoop={true}
WTF how

2020-10-01 18:26 UTC, kavimaluskam commented on src/components/Location/index.js
> +      <Carousel showStatus={false} dynamicHeight autoPlay infiniteLoop>
You mean `dynamicHeight`, `autoPlay`, `infiniteLoop` ? 

I think it's default as true in normal cases ?

https://github.com/leandrowd/react-responsive-carousel/blob/9a7677fb8bcbe456baf25cb7fc2e30c243e19c30/src/main.tsx#L8-L9

2020-10-03 06:47 UTC, victor77dev approved these changes

2020-10-03 06:48 UTC, merged